### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by catb0t** [ttb-pot8o/potato-id#7]
- [ ] HTML form input to request a potato record from the server given a UID
  - [ ] render a) queried potato and history and b) (less important) characteristically similar potatoes 
- [ ] improve / modernize page / table layout and style 
- [ ] HTML form input to create a new potato record with inputs for `evident` features: mass, vol, introduced time and place, surface image, and heightmap
- [ ] use potato surface images 
- [ ] heightmap data structure idea
